---
title: "Aides Drug"
author: "Hazel"
date: "12/5/2025"
output: html_document
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
triUmp <-read.csv(file="triUmpsal.csv",header=TRUE)
```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?.  If you skimp in this section expect to be marked down in your grade. Paint a picture of the project a couple of paragraphs is expected!-->

A new  preventative aides drug (triUmpsal) is under test in clinical trials. Consider only the females, does this drug seem effective?  Hint - use dplyr to obtain that subpopulation with the filter command.

# Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method. Discuss what data manipulations may be needed for example subsetting or other binning procedures and what sort of graphical displays and inferential tools will be used!-->

I've noticed that this assignment is using the 'Categorical-Categorical' helper files data; in order to solve 

# Results

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Descriptive Results

### Graphical Descriptive Results

<!--Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question. Bottom line is to explain the features of the graph that are relevant to conforming or departing to what is expected by your null hypothesis !-->

When I observed the chart, I realized that the people who got the drug, which is about 58%, actually got aids. And shockingly, those who got the placebo, which are 40%, and got aids are lower than the ones who got drugs and have aids. This told me that the drug is simply not working and is giving the opposite of what it is supposed to give. 

### Numerical Descriptive Results

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->

After looking at the numerical results, I saw that it agrees with the graphical results and proves more that the drug(s) is not working properly. As seen, 58.82% of people that got the drug still got aids. 

## Inferential Results

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->

After looking at the Inferential Results, I observed that it gave me 3 tests (Pearson's Chi-squared, Chi-Square Statistic, and Fisher's Exact Test). What I had noticed is that all 3 tests gave me low P-values - which shows there is no significant difference between getting the drug or the placebo. 
In other words, the drug isn't working properly. What also supported the observation is that 'Fisher's Exact Test' gave me an odds ratio, which was 1.543902, and the odds ratio is the probability of getting aids due to the drug. 


# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
